//! Integration tests for the `look_at` function-like macro.

use core::ops::Add;

use look_at::look_at;

/// Architecture-specific definitions used by the forwarding declarations.
///
/// Tests access every definition through output generated by `look_at`.
mod arch {
    use core::ops::Add;

    /// Implements architecture-specific forwarding targets.
    ///
    /// The definitions are imported or called by the surrounding test macro invocation.
    pub(crate) fn generic<T>(left: T, right: T) -> T
    where
        T: Add<Output = T>,
    {
        left + right
    }

    /// Creates a fixed-size array.
    ///
    /// The function exercises forwarding of a const generic argument.
    pub(crate) fn array<const N: usize>(value: u8) -> [u8; N] {
        [value; N]
    }

    /// Borrows a value.
    ///
    /// The function preserves both a lifetime and a potentially unsized type parameter.
    #[allow(clippy::needless_lifetimes)]
    pub(crate) fn borrow<'a, T: ?Sized>(value: &'a T) -> &'a T {
        value
    }

    /// Reads a value through a raw pointer.
    ///
    /// Callers must provide a valid pointer to a live `u32`.
    pub(crate) unsafe fn read(pointer: *const u32) -> u32 {
        // SAFETY: The caller provides the validity guarantee.
        unsafe { *pointer }
    }

    /// Doubles an integer through the C ABI.
    ///
    /// The function verifies preservation of an explicit ABI.
    pub(crate) extern "C" fn abi(value: u32) -> u32 {
        value * 2
    }

    /// Increments an integer.
    ///
    /// The function verifies ordinary public forwarding.
    pub(crate) fn nested(value: u32) -> u32 {
        value + 1
    }

    /// Decrements an integer.
    ///
    /// The function verifies forwarding without an intermediate module.
    pub(crate) fn flattened(value: u32) -> u32 {
        value - 1
    }

    /// Adds a pair of integers.
    ///
    /// The function receives a tuple after the wrapper normalizes a tuple pattern.
    pub(crate) fn pair_sum(pair: (u32, u32)) -> u32 {
        pair.0 + pair.1
    }

    /// Returns the byte length of a string.
    ///
    /// The function receives ownership after the wrapper normalizes a `ref` pattern.
    pub(crate) fn string_len(value: String) -> usize {
        value.len()
    }

    /// An imported type alias.
    ///
    /// The alias verifies direct type re-exporting.
    pub type Value = u32;

    /// An imported generic type alias.
    ///
    /// The alias verifies preservation of generic type parameters during re-exporting.
    pub type GenericValue<T> = Option<T>;

    /// An imported structure.
    ///
    /// The structure is `Send` and therefore satisfies the requested assertion.
    pub struct ArchStruct;

    /// An imported enumeration.
    ///
    /// The enumeration exposes one variant for use by the test.
    pub enum ArchEnum {
        /// The only test variant.
        Variant,
    }

    /// An imported union.
    ///
    /// The union carries a single `u32` field for test reads.
    pub union ArchUnion {
        /// The active union field.
        pub value: u32,
    }

    /// An imported constant.
    ///
    /// The value verifies direct constant re-exporting.
    pub const VALUE: u32 = 9;

    /// A renamed imported type alias.
    ///
    /// The alias verifies forwarding of a `use` declaration.
    pub use self::Value as ReexportedValue;
}

look_at! {
    @crate::arch:
    /// Adds two generic values through the selected implementation.
    ///
    /// The wrapper preserves type generics and a where clause.
    fn generic<T>(left: T, right: T) -> T where T: Add<Output = T>;
    /// Creates a const-generic array through the selected implementation.
    ///
    /// The wrapper forwards the const parameter in a turbofish.
    fn array<const N: usize>(value: u8) -> [u8; N];
    /// Borrows a generic value through the selected implementation.
    ///
    /// The wrapper preserves explicit lifetime parameters.
    #[allow(clippy::needless_lifetimes)] fn borrow<'a, T: ?Sized>(value: &'a T) -> &'a T;
    /// Reads a pointer through the selected unsafe implementation.
    ///
    /// Callers retain responsibility for pointer validity.
    unsafe fn read(pointer: *const u32) -> u32;
    /// Doubles a value through the selected C ABI implementation.
    ///
    /// The wrapper retains its explicit ABI.
    extern "C" fn abi(value: u32) -> u32;
    /// Increments a value through the selected implementation.
    ///
    /// The wrapper is publicly visible within the test crate.
    pub fn nested(value: u32) -> u32;
    /// Decrements a value through the selected implementation.
    ///
    /// The wrapper is emitted directly at the invocation location.
    fn flattened(value: u32) -> u32;
    /// Adds a tuple through the selected implementation.
    ///
    /// The tuple pattern becomes a readable forwarding parameter.
    fn pair_sum((left, right): (u32, u32)) -> u32;
    /// Measures an owned string through the selected implementation.
    ///
    /// The `ref` pattern becomes its declared readable name.
    fn string_len(ref value: String) -> usize;
    /// An imported type alias.
    ///
    /// The placeholder resolves to the target module's definition.
    pub type Value;
    /// An imported generic type alias.
    ///
    /// The placeholder retains the target alias's generic interface.
    pub type GenericValue<T>;
    /// An imported structure with a compile-time trait assertion.
    ///
    /// Expansion verifies that the target structure implements `Send`.
    pub type ArchStruct: Send;
    /// A disabled assertion used to verify attribute propagation.
    ///
    /// Both the re-export and its anonymous assertion must be removed by this configuration.
    #[cfg(any())]
    pub type ArchStruct: Iterator;
    /// An imported enumeration with a compile-time trait assertion.
    ///
    /// Expansion verifies that the target enumeration implements `Send`.
    pub type ArchEnum: Send;
    /// An imported union.
    ///
    /// The placeholder resolves to the target module's definition.
    pub type ArchUnion;
    /// An imported constant with a compile-time type assertion.
    ///
    /// Expansion verifies the target constant's declared `u32` type.
    pub const VALUE: u32;
    /// A use tree resolved below the selected target module.
    ///
    /// The declaration imports the target's renamed type alias.
    pub use ReexportedValue;
}

/// Verifies forwarding for supported function signatures.
///
/// The assertions cover generics, ABIs, unsafe functions, and nontrivial parameter patterns.
#[test]
fn forwards_supported_function_signatures() {
    assert_eq!(generic(2_u64, 3), 5);
    assert_eq!(array::<3>(4), [4, 4, 4]);

    let text = String::from("borrowed");
    assert_eq!(borrow(&text), "borrowed");

    let value = 7;
    // SAFETY: `value` remains alive for the duration of the call.
    assert_eq!(unsafe { read(&raw const value) }, 7);

    assert_eq!(abi(4), 8);
    assert_eq!(nested(4), 5);
    assert_eq!(flattened(4), 3);
    assert_eq!(pair_sum((2, 3)), 5);
    assert_eq!(string_len(String::from("hello")), 5);
}

/// Verifies forwarding for supported non-function items.
///
/// The assertions exercise aliases, nominal types, constants, and use declarations.
#[test]
fn forwards_non_function_items() {
    let _: Value = 1;
    let _: GenericValue<u32> = Some(1);
    let _: ReexportedValue = 2;
    let _ = ArchStruct;
    let _ = ArchEnum::Variant;
    let union = ArchUnion { value: 3 };
    // SAFETY: `value` is the active union field.
    assert_eq!(unsafe { union.value }, 3);
    assert_eq!(VALUE, 9);
}
