[workspace]
resolver = "3"
members = [
    "ecraos",
    "ecraos-loader",
    "exboot/exboot",
    "exboot/exboot-macros",
    "exboot/exboot-multiboot-x86_64", "exbuddy", "exslab", "expt", "size-disp", "memory_range_set", "expercpu/expercpu", "expercpu/expercpu_macros"
, "dyn_static_traits", "maybe_non_generic", "exarch", "expalloc_trait", "exboot/exboot-none-riscv64"]

[workspace.dependencies]
cfg-if = "1.0"
kspin = "0.2"
lazyinit = "0.2"
log = "0.4"
memory_addr = "0.4.1"
thiserror = { version = "2.0", default-features = false }
