[workspace]
resolver = "3"
members = [
    "ecraldr/ecraldr",
    "ecraldr/ecraldr-riscv64-none",
    "ecraldr/ecraldr-x86_64-multiboot",
    "ecraldr/ecraldr_base",
    "ecraldr/ecraldr_base_macros",
    "ecraos",
    "exarch",
    "exbuddy",
    "expalloc_trait",
    "expercpu/expercpu",
    "expercpu/expercpu_macros",
    "expt",
    "exslab",
    "utils/dyn_static_traits",
    "utils/maybe_non_generic",
    "utils/memory_range_set",
    "utils/size_disp",
]
exclude = [
    "ecraldr/ecraldr_build_rs",
]

[workspace.dependencies]
cfg-if = "1.0"
kspin = "0.2"
lazyinit = "0.2"
log = "0.4"
memory_addr = "0.4.1"
thiserror = { version = "2.0", default-features = false }
