[workspace]
resolver = "3"
members = [
    "ecraos",
    "explat/explat",
    "explat/explat-x86_64",
    "ecraos-loader",
    "exboot/exboot",
    "exboot/exboot-macros",
    "exboot/exboot-multiboot-x86_64", "exbuddy", "exslab", "expt", "size-disp", "memory_range_set",
]

[workspace.dependencies]
cfg-if = "1.0"
lazyinit = "0.2"
memory_addr = "0.4.1"
thiserror = { version = "2.0", default-features = false }
