[package]
name = "expt"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if.workspace = true
dyn_static_traits = { path = "../dyn_static_traits" }
expalloc_trait = { path = "../expalloc_trait" }
heapless = "0.9"
maybe_non_generic = { path = "../maybe_non_generic" }
memory_addr.workspace = true
page_table_entry = "0.6.1"
thiserror.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86 = "0.52"
