[package]
name = "ecraos"
version = "0.1.0"
edition = "2024"

[dependencies]
bitmaps = { version = "3.2.1", default-features = false }
heapless = "0.9"
exarch = { path = "../exarch" }
exboot = { path = "../exboot/exboot" }
exbuddy = { path = "../exbuddy" }
expalloc_trait = { path = "../expalloc_trait" }
expt = { path = "../expt" }
exslab = { path = "../exslab" }
kspin = "0.2"
lazyinit.workspace = true
log = "0.4"
memory_addr.workspace = true
memory_range_set = { path = "../memory_range_set" }
size-disp = { path = "../size-disp" }
thiserror.workspace = true
