//! Kernel trap (interrupts and exceptions) handling.
//!
//! # Terminology
//!
//! A variety of terms have been used by different architectures and operating systems to refer to
//! events that cause a diversion from the normal flow of execution. Interrupts, exceptions, traps,
//! and faults, to name a few.
//!
//! ecraOS uses a terminology scheme that is similar to the one used by the RISC-V architecture.
//!
//! ## Trap
//!
//! ecraOS uses the term "trap" to refer to any event that causes a diversion from the normal flow
//! of execution. This includes interrupts, exceptions, and system calls. The term "trap" is used to
//! encompass all these events in a unified manner.
//!
//! ## Interrupt
//!
//! ecraOS uses the term "interrupt" to refer to an external asynchronous event that is generated by
//! hardware devices, and maybe other CPU cores.
//!
//! ## Exception
//!
//! ecraOS uses the term "exception" to refer to a synchronous event that is generated by the CPU
//! itself, usually as a result of executing an instruction. Exceptions can be caused by various
//! conditions, such as invalid memory access, division by zero, or illegal instructions.
//!
//! ## Irq
//!
//! ecraOS uses the term "irq" (or "global irq" as a synonym) to refer to interrupts that are not
//! generated by the CPU itself, or other CPU cores, or its local devices (such as timers). This
//! generally includes interrupts from external (peripheral) devices.

pub mod irq;

use exarch::trap::{
    Exception, ExceptionHandler, GlobalIrqHandler, HandlerSlots, LocalInterrupt,
    LocalInterruptHandler, Trap, TrapDisposition, TrapFrame, TrapFrameAccess, TrapHandler,
    irq::ArchIrq,
};

/// The kernel-owned semantic handler slots.
///
/// The slots are initialized during boot and may be replaced or cleared during controlled
/// lifecycle transitions.
static HANDLERS: HandlerSlots = HandlerSlots::new();

/// Registers or replaces one semantic kernel handler.
///
/// Registration must complete before the corresponding local interrupt source is enabled. Handler
/// slots may be replaced or cleared during controlled lifecycle transitions.
pub fn register<H: TrapHandler>(handler: H) {
    HANDLERS.register(handler)
}

/// Dispatches a decoded semantic trap through the kernel-owned handler slots.
///
/// Unknown interrupt values are completed by architecture code and never enter this function.
pub fn handle(frame: &mut TrapFrame, trap: Trap) -> TrapDisposition {
    HANDLERS.dispatch(frame, trap)
}

/// Bridges architecture trap entry to the kernel semantic handler table.
///
/// The implementation is generated as the `exarch::trap` crate-interface provider.
struct TrapHandlerImpl;

#[crate_interface::impl_interface]
impl exarch::trap::KernelTrapIf for TrapHandlerImpl {
    fn handle(frame: &mut TrapFrame, trap: Trap) -> TrapDisposition {
        crate::trap::handle(frame, trap)
    }
}

/// Handles exceptions that have no recoverable kernel subsystem yet.
///
/// Fatal exceptions panic directly, including unknown synchronous causes, so they cannot return
/// into a repeatedly faulting instruction.
pub fn default_exception_handler(frame: &mut TrapFrame, exception: Exception) -> TrapDisposition {
    match exception {
        Exception::Breakpoint => {
            log::debug!("#BP @ {:?}", frame.instruction_pointer());
            TrapDisposition::Handled
        }
        exception => panic!(
            "Unhandled exception {:?} @ {:?}, user={}",
            exception,
            frame.instruction_pointer(),
            frame.is_user()
        ),
    }
}

/// Converts the semantic local timer trap into the periodic timer callback.
fn handle_local_interrupt(_frame: &mut TrapFrame, interrupt: LocalInterrupt) -> TrapDisposition {
    match interrupt {
        LocalInterrupt::Timer => {
            crate::task::timer_tick();
            crate::timer::timer_tick();
            crate::task::timer_interrupt_exit();
            TrapDisposition::Handled
        }
        LocalInterrupt::Software => TrapDisposition::Unhandled,
    }
}

/// Handles global interrupts through the existing architecture source registry.
///
/// The registry migration keeps source handlers in the kernel-facing boundary while preserving the
/// tested controller lifecycle during this transition.
pub fn default_global_irq_handler(frame: &mut TrapFrame, irq: ArchIrq) -> TrapDisposition {
    irq::dispatch(frame, irq)
}

/// Installs the exception and global semantic handlers.
///
/// The local-interrupt slot is installed before timer arming.
pub fn init() {
    irq::init();

    _ = register::<ExceptionHandler>(default_exception_handler);
    _ = register::<LocalInterruptHandler>(handle_local_interrupt);
    _ = register::<GlobalIrqHandler>(default_global_irq_handler);
}
