//! Kernel trap (interrupts and exceptions) handling.
//!
//! # Terminology
//!
//! A variety of terms have been used by different architectures and operating systems to refer to
//! events that cause a diversion from the normal flow of execution. Interrupts, exceptions, traps,
//! and faults, to name a few.
//!
//! ecraOS uses a terminology scheme that is similar to the one used by the RISC-V architecture.
//!
//! ## Trap
//!
//! ecraOS uses the term "trap" to refer to any event that causes a diversion from the normal flow
//! of execution. This includes interrupts, exceptions, and system calls. The term "trap" is used to
//! encompass all these events in a unified manner.
//!
//! ## Interrupt
//!
//! ecraOS uses the term "interrupt" to refer to an external asynchronous event that is generated by
//! hardware devices, and maybe other CPU cores.
//!
//! ## Exception
//!
//! ecraOS uses the term "exception" to refer to a synchronous event that is generated by the CPU
//! itself, usually as a result of executing an instruction. Exceptions can be caused by various
//! conditions, such as invalid memory access, division by zero, or illegal instructions.
